### ISSUE TITLE
Install instructions fail after upgrading to Ventura

### ISSUE THREAD

**Issue by sandhujasmine** [mhsmith/InstructPix2Pix#1]
- I used the readme on Monterey to run the application. It worked as documented in the readme.
- I upgraded to Ventura.
- Since I'm experimenting with things, I tried to run it again in a new environment and now I get an error. 

I'm a conda user so I created a conda environment with the constraints on python, then pip installed briefcase in that conda env and ran `briefcase dev`. This updated packages in the conda env and worked as expected before I did the ventura upgrade. Commands I ran:

```
conda create -n briefcase 'python>=3.7,<3.11'
conda activate briefcase
pip install briefcase
briefcase dev
```

If I go into the briefcase environment, created previously, I can successfully run the application as it installed the dependencies correctly. However, when I created a new env after Ventura upgrade, I get an error:
```
conda create -n briefcase2 'python>=3.7,<3.11'
conda activate briefcase
pip install briefcase
(briefcase2) jasmine@Jasmines-MacBook-Pro HackdaysAIImageGenerator % briefcase dev

[hackdays_ai] Starting in dev mode...
===========================================================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jasmine/miniconda3/envs/briefcase2/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Users/jasmine/miniconda3/envs/briefcase2/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/jasmine/miniconda3/envs/briefcase2/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jasmine/projects/HackdaysAIImageGenerator/src/hackdays_ai/__main__.py", line 1, in <module>
    from hackdays_ai.app import main
  File "/Users/jasmine/projects/HackdaysAIImageGenerator/src/hackdays_ai/app.py", line 6, in <module>
    import toga
ModuleNotFoundError: No module named 'toga'

Problem running app hackdays_ai.

Log saved to /Users/jasmine/projects/HackdaysAIImageGenerator/logs/briefcase.2023_02_15-16_02_15.dev.log
```

It appears the dependencies listed in the pyproject.toml didn't get installed. I haven't dug into it yet but wanted to log it. And curious if it is reproducible for others.

[briefcase.2023_02_15-16_02_15.dev.log](https://github.com/mhsmith/HackdaysAIImageGenerator/files/10750989/briefcase.2023_02_15-16_02_15.dev.log)

**Comment by mhsmith** [comment]
Hi Jasmine,

`briefcase dev` only has a limited ability to install dependencies automatically (https://github.com/beeware/briefcase/issues/881), but you should be able to install them manually by running `briefcase dev -r`.

**Comment by sandhujasmine** [comment]
Aah - I see, so because I had previously run `briefcase dev` - it found the `src/hackdays_ai.dist-info`, it didn't reinstall dependencies in the new environment.

`briefcase dev -r` will install dependencies from the pyproject.toml which is what I needed. Thanks!
